[#5] Product, Category 도메인 기본 CRUD API 구현 및 테스트 작성
f-lab-edu/event-blackfriday pull request #14
Opened 2024-11-16 19:06 UTC by jaeyeonme

- [x] #8 

## Changes

- [x] Domain Layer
   - Category, Product 엔티티 유즈케이스 변경으로 인해 리팩토링
   - SQL Restriction 적용하여 논리적 삭제 구현
   - Category, Product 단방향 매핑 구현
   - Constants 클래스로 매직넘버 관리

- [x] Repository Layer
   - ProductRepository 기본 CRUD 및 검색 쿼리 구현
   - CategoryRepository 기본 CRUD 구현
   - CategoryClosure N+1 문제 해결을 위한 Join Fetch 적용
   - findByNameContainingIgnoreCase 등 검색 쿼리 구현

- [x] Service Layer
   - CategoryService Closure Table 기반 계층 구조 구현
   - ProductService 재고 관리 로직 구현
   - 각 도메인별 validation 로직 구현
   - @Transactional 적용하여 트랜잭션 관리

- [x] DTO
   - Request/Response DTO 분리
   - 목록/상세/재고 Response 분리
   - Bean Validation 적용
   - from() 메서드로 엔티티 변환 구현

- [x] Controller Layer
   - REST API 엔드포인트 구현
   - @Valid로 요청 검증

- [x] Test Layer
   - Service: Kotest BDD + mockK로 테스트 구현
   - Controller: .http 파일로 API 테스트 구현

2024-11-17 14:13 UTC, f-lab-saponin requested changes
고생하셨습니다!! 🎉
DB 인프라 구현 준비를 위해, 작성하신 엔티티는 sql DDL 문 파일을 따로 관리하시면 좋을 것 같아요.

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/dto/CategoryDto.kt
> +    val displayOrder: Int,
카테고리의 노출순서는 홈화면 같은곳의 메뉴에서 보여질 순서인가요?

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    var displayOrder: Int = 0,
둘다 기본값을 통일하면 어떨까요?

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +    @Transactional(readOnly = true)
이것의 장점은 무엇이길래 사용하셨을까요?

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +        return categoryClosureRepository.findByAncestorIdAndDepthFetchJoin(parentId, 1)
여기 매직넘버가 보이는데, 무슨의미일까요~?

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +        }
이건 무슨 작업을 하는 건지 설명해주실 수 있을까요?

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/dto/ProductDto.kt
> +    val price: BigDecimal,
가격은 1원 이상인건가요~?

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/resources/application.yml
> +      on-profile: local
profiles.active, config.activate.on-profile 혼용해서 쓰고있는데, deprecated 된거는 사용하지 않았으면 좋겠네요~!

2024-11-17 14:13 UTC, f-lab-saponin commented on src/main/resources/application.yml
> +        web-allow-others: false
db 도 어서 구축해보고 disabled 하시죠! 😀

2024-11-17 14:13 UTC, f-lab-saponin commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/category/controller/CategoryController.http
> +}
👍

2024-11-17 14:13 UTC, f-lab-saponin commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryServiceTest.kt
> +class CategoryServiceTest : BehaviorSpec({
👍

2024-11-18 08:28 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/dto/CategoryDto.kt
> +    val displayOrder: Int,
네 맞습니다!

```markdown
전자제품 (displayOrder: 0)
  └── 노트북 (displayOrder: 0)
  └── 스마트폰 (displayOrder: 1)
의류 (displayOrder: 1)
  └── 남성의류 (displayOrder: 0)
  └── 여성의류 (displayOrder: 1)
  ```
  
  이걸 생각해서 넣었습니다.

2024-11-18 08:30 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    var displayOrder: Int = 0,
통일된 값으로 맞추겠습니다

2024-11-18 08:49 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +    @Transactional(readOnly = true)
`@Transactional(readOnly = true)` 같은 경우에는, JPA가 조회 성능을 최적화 할 수 있고, 실수로 데이터가 변경되는 것을 방지하기 위해서 조회 메서드에만 사용하는 것으로 알고 있습니다.! 

그래서 `getCategories()`, `getSubCategories()`, `getCategoryTree()` 모두 조회 메서드라서 사용했습니다.

2024-11-18 09:05 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +        return categoryClosureRepository.findByAncestorIdAndDepthFetchJoin(parentId, 1)
매직넘버로 바꾸겠습니다!

예를 들어 다음과 같은 카테고리 구조가 있다고 할 때:

```markdown
[카테고리 구조]
전자제품 (depth=1)
├── 컴퓨터 (depth=2)
│   ├── 노트북 (depth=3)
│   └── 데스크탑 (depth=3)
└── 모바일 (depth=2)
    └── 스마트폰 (depth=3)
```

[Closure Table 관계]
ancestor  | descendant | depth | 설명
----------|------------|-------|----------------
전자제품   | 전자제품    | 0     | 자신과의 관계
전자제품   | 컴퓨터      | 1     | 직접 하위 관계 ✅
전자제품   | 모바일      | 1     | 직접 하위 관계 ✅
전자제품   | 노트북      | 2     | 간접 하위 관계
전자제품   | 데스크탑    | 2     | 간접 하위 관계
전자제품   | 스마트폰    | 2     | 간접 하위 관계


getSubCategories(전자제품)을 호출하면 depth=1인 관계만 조회하므로
직접 하위 카테고리인 컴퓨터, 모바일만 반환됩니다.

2024-11-19 01:06 UTC, f-lab-saponin requested changes
추가리뷰 드립니다 :)

2024-11-19 01:06 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +    @Transactional(readOnly = true)
혹시 조회 성능을 어떻게 최적화하는지 말씀해주실 수 있으신가요?

2024-11-19 01:06 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +        return categoryClosureRepository.findByAncestorIdAndDepthFetchJoin(parentId, 1)
그럼 직접하위관계만 가져온다고 메소드에도 명시했으면 좋을 것 같아요 :)

2024-11-19 03:46 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +    @Transactional(readOnly = true)
`@Transactional(readOnly = true)` 속성을 사용하면 JPA가 제공하는 읽기 전용 최적화를 활용할 수 있어서 사용했습니다.

`@Transactional(readOnly = true)` 장점
1. 변경감지(Dirty Checking)를 하지 않아서 성능상 이점이 있고
2. 실수로 데이터가 변경되는 것을 방지할 수 있습니다

2024-11-19 03:48 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +        return categoryClosureRepository.findByAncestorIdAndDepthFetchJoin(parentId, 1)
네 그렇게 수정해보겠습니다!

2024-11-19 05:14 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +        }
1. 새로 생성된 카테고리의 자기 참조 관계를 생성해서
2. 부모 카테고리가 있다면?
 - 부모의 모든 closure 관계들을 가져와서
 - depth를 1씩 증가시켜서 추가시킵니다!

이거를 리팩토링 해보겠습니다.

2024-11-19 06:09 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/dto/ProductDto.kt
> +    val price: BigDecimal,
맞습니다. 상품 가격을 좀 더 올려서 리팩토링 해보겠습니다.

2024-11-19 06:19 UTC, jaeyeonme commented on src/main/resources/application.yml
> +      on-profile: local
넵 바로 수정해보겠습니다!

2024-11-19 06:29 UTC, jaeyeonme commented on src/main/resources/application.yml
> +        web-allow-others: false
다음 PR을 바로 CI/CD 할건데, 그때 DB도 같이 구축하는걸로 하겠습니다.

2024-11-19 06:31 UTC, jaeyeonme commented
멘토님 요청드리고, 그 다음것을 다시 고친게 있습니다!

2024-11-19 14:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +    @Transactional(readOnly = true)
네 감사합니다 이대로 가시죠!!

2024-11-19 14:14 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/dto/ProductDto.kt
> +    val price: BigDecimal,
단순 궁금해서 여쭤본거라 원하시는 의도대로 하셔도 좋을 것 같아요 ☺️

2024-11-19 14:15 UTC, f-lab-saponin approved these changes
고생하셨어요 재연님! 🙂
squash merge 가시죠!

2024-11-19 14:17 UTC, merged