[#6] NCP 배포 환경 구축 및 CI/CD 파이프라인 구성
f-lab-edu/event-blackfriday pull request #15
Opened 2024-11-22 18:07 UTC by jaeyeonme

- [x] #9 

## Architecture
```mermaid
graph TB
    subgraph "NCP Cloud"
        LB[Load Balancer]
        
        subgraph "EC2 #1 (Blue)"
            DC1[Docker Compose]
            N1[Nginx]
            B1[Blue App :8080]
            DB1[(MySQL :3306)]
            
            N1 --> B1
            B1 --> DB1
        end
        
        subgraph "EC2 #2 (Green)"
            DC2[Docker Compose]
            N2[Nginx]
            G2[Green App :8080]
            DB2[(MySQL :3306)]
            
            N2 --> G2
            G2 --> DB2
        end
        
        LB --> N1 & N2
    end
```

## Changes

### Infrastructure Layer
- [x] NCP 인프라 구성
  - VPC/Subnet 네트워크 설정
  - Blue/Green EC2 인스턴스 설정
  - Load Balancer 구성 및 라우팅 설정
- [x] Docker 환경 구성
  - MySQL 데이터 영속성을 위한 볼륨 설정
  - 컨테이너 간 네트워크 구성

### Docker Environment
- [x] 멀티 컨테이너 아키텍처 구현
  - Nginx Reverse Proxy 설정
  - Spring Boot Application 컨테이너화
  - MySQL Database 컨테이너 구성
- [x] 시스템 안정성 확보
  - ARM64 아키텍처 호환성 구현
  - 네트워크 격리 및 보안 설정

### CI/CD Pipeline
- [x] GitHub Actions 자동화
  - 테스트 및 빌드 검증 자동화
  - Jib 기반 Docker 이미지 최적화
  - Docker Hub 연동 및 이미지 관리
- [x] Blue-Green 배포 전략
  - 무중단 배포 스크립트 구현
  - 자동화된 헬스체크 시스템
- [x] 보안 관리
  - GitHub Secrets를 통한 환경변수 관리
  - 접근 권한 및 인증 설정

### Application Configuration
- [x] 환경 설정 최적화
  - local/dev 프로파일 분리
  - JPA/Hibernate 설정 구성
- [x] 데이터베이스 관리
  - MySQL 초기 스키마 자동화

2024-11-23 10:58 UTC, f-lab-saponin requested changes
제가 직접 테스트해보진 못하고 코드위주로 리뷰드렸는데 일단 확인부탁드려요!
고생하셨습니다 😀😀

2024-11-23 10:58 UTC, f-lab-saponin commented on .github/workflows/deploy.yml
> +    branches: [ main ]
branches 정의 양식이 통일 되면 어떨까요? 😀

2024-11-23 10:58 UTC, f-lab-saponin commented on .github/workflows/deploy.yml
> +        run: ./gradlew test
이전에 캐시된 것이 있는지 방지하기 위해서 test 전 clean 하면 좋아 보이는데 어떠실까요? 😀

2024-11-23 10:58 UTC, f-lab-saponin commented on .github/workflows/deploy.yml
> +          username: root
(옵션)
root 계정은 모든 권한이 포함되어있으니, 이를 악용하면 위험할 수 있을 것 같아요.
서버에 들어가서 배포용 계정을 만들어보고, 배포용 계정으로 배포해보면 어떨까요? 🙂

2024-11-23 10:58 UTC, f-lab-saponin commented on .github/workflows/deploy.yml
> +          exit 1
애플리케이션 시작하자마자 헬스체크하면 무조건 한 번은 실패할 것 같아요.
처음에는 시간을 두고 헬스체크해보는게 어떨까요? 😀

만약 쿠버네티스를 사용하면 이를 어떻게 하는지도 조사해보면 좋을것같아요.
cf) readiness, liveness probe

2024-11-23 10:58 UTC, f-lab-saponin commented on build.gradle.kts
> +jib {
👍 jib 장점이 뭘까요?

2024-11-23 10:58 UTC, f-lab-saponin commented on build.gradle.kts
> +        tags = setOf("latest", version.toString())
이건 무슨 버전일까요?
deploy.yml 에서 주입해주는 버전이랑은 달라보이네요~? 😊

2024-11-23 10:58 UTC, f-lab-saponin commented on src/main/resources/application.yml
> +      on-profile: dev
배포한 서버를 프로덕션서버로 하는게 어떨까요~?

2024-11-23 10:58 UTC, f-lab-saponin commented on src/main/resources/application.yml
> +      ddl-auto: update
👍 프로덕션 서버로 했다면 none 으로 하는것도 함부로 생성되지 않도록 영향을 막을 수 있어서 권장되기도 합니다 :)

2024-11-23 10:58 UTC, f-lab-saponin commented on src/main/resources/application.yml
> +    show-sql: true
만약 프로덕션 이라면 이건 false 여도 괜찮겠죠~?

2024-11-23 10:58 UTC, f-lab-saponin commented on scripts/deploy/deploy.sh
> +done
deploy.yml 에서 한 것과 겹치는 부분이 좀 있어보이네요~?
이 스크립트는 수동배포할 때 사용되는것인가요?

2024-11-23 10:58 UTC, f-lab-saponin commented on docker/ngnix/app.conf
> +        proxy_set_header Connection "upgrade";
이게 각각 왜 필요한지 혹시 한번 설명해주실 수 있을까요? 🧐

2024-11-23 10:58 UTC, f-lab-saponin commented on docker/ngnix/app.conf
> +    }
/health 로 들어오면 바로 200으로 응답하는데
의도된건가요~?

2024-11-23 10:58 UTC, f-lab-saponin commented on docker/docker-compose.yml
> +  mysql_data:
뭔가 미완성 되어있는것 같아요!

2024-11-23 11:24 UTC, jaeyeonme commented on .github/workflows/deploy.yml
> +    branches: [ main ]
양식 통일 시켜 보겠습니다! 😀

2024-11-23 11:26 UTC, jaeyeonme commented on .github/workflows/deploy.yml
> +        run: ./gradlew test
`Clean` 태스크를 추가하면, 이전 빌드에서 생성된 파일들이 삭제되서 깨끗한 상태가 되겠군요! 수정하겠습니다 😀

2024-11-23 11:29 UTC, jaeyeonme commented on .github/workflows/deploy.yml
> +          username: root
배포용 계정으로 바꿔보겠습니다~

2024-11-23 11:48 UTC, jaeyeonme commented on .github/workflows/deploy.yml
> +          exit 1
지금은 VM에 Docker-Compose로 구성되어 있어서, Docker-Compose의 healthcheck를 통해서 컨테이너에서 상태 체크를 한 것이었습니다! 다시 수정해보겠습니다. 😀

아직 K8S는 고려하지 않았습니다!

2024-11-23 12:22 UTC, jaeyeonme commented on build.gradle.kts
> +jib {
Jib을 이용하면 Dockerfile 없이 바로 컨테이너 이미지가 생성이 되어서, 빌드 프로세스가 단순화됩니다!

1. Docker 빌드 흐름: Dockerfile -> Build Context -> Container Image (Docker cahce) -> Container Image)
2. Jib 빌드 흐름: Project ->Container Image (registry)

2024-11-23 12:24 UTC, jaeyeonme commented on build.gradle.kts
> +        tags = setOf("latest", version.toString())
`github.sha` 로 통일시키겠습니다~

2024-11-23 12:27 UTC, jaeyeonme commented on src/main/resources/application.yml
> +      on-profile: dev
넵 그걸로 프로덕션서버로 하겠습니다~

2024-11-23 12:55 UTC, jaeyeonme commented on src/main/resources/application.yml
> +      ddl-auto: update
그렇군요! none 으로 바꾸겠습니다 :)

2024-11-23 12:56 UTC, jaeyeonme commented on src/main/resources/application.yml
> +    show-sql: true
이것도 바꾸겠습니다 :)

2024-11-23 12:58 UTC, jaeyeonme commented on scripts/deploy/deploy.sh
> +done
넵! 그런데, Github Actions를 통한 자동 배포에서만 사용해도 될 것 같습니다! 삭제하겠습니다~

2024-11-23 13:09 UTC, jaeyeonme commented on docker/ngnix/app.conf
> +        proxy_set_header Connection "upgrade";
1. Proxy Pass 및 기본 헤더 설정:
 - proxy_pass http://app:8080: Docker 네트워크 내 Spring Boot 앱으로 요청 전달
 - proxy_set_header Host $host: 실제 요청된 호스트 정보를 백엔드에 전달
 - proxy_set_header X-Real-IP $remote_addr: 실제 클라이언트 IP를 백엔드에 전달
 
2. 프록시 추적 및 프로토콜 설정:
 - X-Forwarded-For: 클라이언트와 프록시 서버들의 IP 목록 전달
 - X-Forwarded-Proto: 원본 요청의 프로토콜(http/https) 정보 전달

3. WebSocket 지원 설정:
 - proxy_http_version 1.1: HTTP/1.1 프로토콜 사용
 - Upgrade & Connection: WebSocket 연결 업그레이드 처리
 - 실시간 양방향 통신이 필요한 경우에 필수

으로 알고 있습니다! 그런데, 우리 프로젝트에서는 HTTPS 처리를 안해놔서 몇개 리팩토링 해보겠습니다~

2024-11-23 13:11 UTC, jaeyeonme commented on docker/ngnix/app.conf
> +    }
이렇게 되면 Spring Boot 애플리케이션의 상태와 관계없이 무조건 200 OK 를 반환하겠군요! 수정하겠습니다~

2024-11-23 13:13 UTC, jaeyeonme commented on docker/docker-compose.yml
> +  mysql_data:
실제 호스트 시스템의 어느 경로에 저장할지 지정되어있지 않군요! 수정하겠습니다~

2024-11-23 18:34 UTC, jaeyeonme commented
멘토님 리뷰 요청 드리고 Workflow 수정한 것이 있습니다!

2024-11-24 14:21 UTC, f-lab-saponin commented on docker/ngnix/app.conf
> +        proxy_set_header Connection "upgrade";
웹소켓 지원설정은 필요할까요?_

2024-11-25 03:42 UTC, jaeyeonme commented on docker/ngnix/app.conf
> +        proxy_set_header Connection "upgrade";
현재 프로젝트에서 WebSocket을 사용하고 있지 않으니 불필요하군요! 제거하겠습니다.

2024-11-28 17:31 UTC, jaeyeonme commented
```mermaid
flowchart TB
    subgraph "NCP Cloud Infrastructure"
        LB[Load Balancer :80] -->|"Health Check"| TG[Target Group :8080]
        
        subgraph ASG["Auto Scaling Group"]
            TG -->|"Traffic Distribution"| EC1
            TG -->|"Traffic Distribution"| EC2
            
            subgraph "EC2 Instance 2"
                EC1[EC2] -->|"docker-compose up"| DC1[Docker Compose]
                DC1 --> APP1[Spring Boot :8080]
                DC1 --> DB1[MySQL :3306]
                APP1 --> DB1
            end
            
            subgraph "EC2 Instance 1"
                EC2[EC2] -->|"docker-compose up"| DC2[Docker Compose]
                DC2 --> APP2[Spring Boot :8080]
                DC2 --> DB2[MySQL :3306]
                APP2 --> DB2
            end
        end
    end
```

애플리케이션의 배포 전략을 **Blue-Green**에서 **Rolling Update** 방식으로 전환하였습니다.
기존 Blue-Green 배포 방식에서는 두 가지 주요한 운영상의 문제점이 있었습니다
1. 리소스 효율성 문제: Blue와 Green 환경을 동시에 유지해야 하는 특성상, 실제 필요 이상의 컴퓨팅 자원을 소비하게 되었습니다. 특히 트래픽을 받지 않는 대기 환경도 계속 가동해야 하는 비효율이 존재했습니다.
2. 복잡한 배포 프로세스: 배포 시 `deploy.sh` 스크립트를 통한 수동 배포 프로세스와 Nginx의 `app.conf` 설정을 통한 포트 전환 로직이 필요했습니다. 이러한 수동 설정들은 배포 과정의 복잡성을 증가시켰습니다.

이러한 문제점들을 해결하기 위해 Auto Scaling Group과 Load Balancer를 활용한 Rolling Update 방식을 도입했습니다. 새로운 배포 방식의 주요 개선사항은 다음과 같습니다:
1. 자동화된 인프라 관리: Auto Scaling Group이 인스턴스의 생성과 종료를 자동으로 관리하면서, 수동으로 작성했던 `deploy.sh` 스크립트가 불필요해졌습니다.
2. 간소화된 설정: Load Balancer가 직접 애플리케이션 포트(8080)로 트래픽을 라우팅하면서, Nginx reverse proxy 설정(`app.conf`)이 제거되었습니다. 이를 통해 설정 관리 포인트가 줄어들고 시스템 복잡도가 감소했습니다.
3. 효율적인 리소스 활용: 필요한 만큼만 인스턴스를 운영할 수 있게 되어 리소스 활용 효율성이 크게 개선되었습니다.

2024-11-30 12:56 UTC, f-lab-saponin approved these changes
정말 고생하셨네요 재연님!
구성이 깔끔한것같아요.
미팅에서 시연되는 모습만 한번봤으면 좋겠네요. 고생하셨습니다 승인드려요!
다음 구현 진행하시죠!

2024-11-30 12:56 UTC, f-lab-saponin commented on .github/workflows/deploy.yml
> +            ${{ runner.os }}-gradle-
뭔가 끊긴것같은데 맞나요~?

2024-11-30 12:56 UTC, f-lab-saponin commented on .github/workflows/deploy.yml
> +          sleep 20
들여쓰기가 필요해보여요 😀

2024-12-01 03:18 UTC, jaeyeonme commented on .github/workflows/deploy.yml
> +            ${{ runner.os }}-gradle-
이렇게 하면, runner.os 값에 따라 접두사가 일치하는 모든 캐시를 복원하려고 시도합니다. runner.os가 ubuntu-latest인 경우, ubuntu-latest-gradle-로 시작하는 모든 캐시 키를 순차적으로 검색하는걸로 알고 있습니다!

구체적인 복원 키를 추가해보겠습니다!

2024-12-01 03:19 UTC, jaeyeonme commented on .github/workflows/deploy.yml
> +          sleep 20
들여쓰기 하겠습니다! 😀

2024-12-01 03:22 UTC, merged