[#7] Member Domain 구현 - 회원 관리 및 Prime 멤버십 시스템
f-lab-edu/event-blackfriday pull request #16
Opened 2024-12-11 16:06 UTC by jaeyeonme

- [x] #10 

## Changes
### Domain Layer
- Member 도메인 핵심 구현
  - Member 엔티티 설계 및 구현 (이메일, 비밀번호, 이름, 멤버십 정보)
  - MembershipType Enum을 통한 회원 등급 관리 (NORMAL, PRIME)

### Application Layer
- [x] 회원 관리 서비스 구현
  - 회원 CRUD 기능 구현
  - 비밀번호 암호화 처리
  - 회원 탈퇴 시 Soft Delete 구현
  - Prime 멤버십 가입/해지 프로세스 구현

### Infrastructure Layer
- [x] Redis 세션 관리
  - Redis 기반 세션 저장소 구현
  - 세션 만료 및 갱신 로직 구현
- [x] Security 설정
  - 인터셉터 기반 인증/인가 처리
  - @LoginRequired, @PrimeOnly 어노테이션 구현
  - CurrentUser 어노테이션을 통한 인증 회원 조회
- [x] API 문서화
  - Swagger 3.0 설정 및 구현
  - API 그룹화 및 태그 설정
  - Security 스키마 설정 (X-Auth-Token)
  - Controller 및 DTO 문서화

### Test Layer
- [x] 테스트 코드 작성
  - MemberServiceTest 구현
  - MembershipServiceTest 구현
  - MemberControllerTest HTTP 테스트 구현

### Configuration
- [x] Redis 설정
  - RedisConfig를 통한 세션 저장소 설정
- [x] Security 설정
  - WebConfig를 통한 인터셉터 및 ArgumentResolver 등록
  - AuthenticationInterceptor 구현
- [x] Swagger 설정
  - SwaggerConfig를 통한 OpenAPI 3.0 설정

2024-12-12 16:09 UTC, f-lab-saponin requested changes
회원과 세션인증, 멤버십 기능을 잘 만드셨네요!
전반적으로 ResponseEntity 는 제거하셔도 될것같아요.
코멘트 드린내용 한번 확인부탁드립니다!!

2024-12-12 16:09 UTC, f-lab-saponin commented on docker/docker-compose.yml
> +        condition: service_healthy
service_healthy 동작이 어떻게 진행되는건가요?

2024-12-12 16:09 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    member_id BIGINT,
상품에 회원아이디는 왜 필요한건가요?

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/PasswordConfig.kt
> +    fun passwordEncoder(): PasswordEncoder = BCryptPasswordEncoder()
조금 더 보안이 강화된 인코더를 활용해볼까요? 🙂

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/RedisConfig.kt
> +    private fun createObjectMapper(): ObjectMapper {
이것도 매번 생성할 필요는 없으니 특정 이름으로 빈으로 등록해놔도 좋을 것 같아요 😀

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/SwaggerConfig.kt
> +                        "X-Auth-Token",
"X-Auth-Token" 자주 쓰이는 것 같은데 상수로 만들어볼까요?

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/WebConfig.kt
> +    override fun addInterceptors(registry: InterceptorRegistry) {
👍

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/interceptor/AuthenticationInterceptor.kt
> +        val sessionId = request.getHeader("X-Auth-Token")
아까 상수로 선언했던것 공통으로 쓰면 좋겠네요 😀

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/interceptor/PrimeMembershipInterceptor.kt
> +        if (!sessionUser.roles.contains("ROLE_PRIME")) {
이것도 상수로하면 좋겠네요 🙂

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/security/session/SessionUser.kt
> +        private const val serialVersionUID = 1L
Serializable 구현 안하면 어떻게 되나요? 잘 동작하는지 궁금하네요

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    fun login(@Valid @RequestBody request: LoginRequest): ResponseEntity<MemberResponse> {
ResponseEntity 는 생략해도 되는것같아요 🙂

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
여긴 제 생각이 맞다면 member 를 DB 로 부터 2번 조회할 것 같은데요
더 좋은 구조가 있을까요?

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/service/MembershipService.kt
> +        httpSession.setAttribute(USER_KEY, SessionUser.from(savedMember))
이거하기 전에 세션에 유저먼저 있는지 확인하면 좋겠네요

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    var memberId: Long? = null,
사용안하는 것 같아요 !

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/resources/application.yml
> +          max-wait: -1ms
마이너스 의미는 뭔가요?

2024-12-12 16:09 UTC, f-lab-saponin commented on src/main/resources/application.yml
> +      cleanup-cron: "0 */30 * * * *"
30분 주기 세션삭제하면 홈페이지둘러보고 있는 손님이 로그인을 자주해야하지 않을까요?

2024-12-12 16:20 UTC, jaeyeonme commented on docker/docker-compose.yml
> +        condition: service_healthy
app1 서비스가 완전히 준비된 후에만 Nginx 가 시작되도록 보장하는 걸고 알고 있습니다!
1. Docker가 app1 컨테이너 시작
2. JVM 구동 및 Spring Boot 애플리케이션 초기화
3. DB 연결
4. 10초 간격으로 Health Check 실행
5. 3번 재시도 내에 health check가 성공하면 'healthy' 상태로 변경
6. app1이 'healthy' 상태가 되면 Nginx 컨테이너 시작

이 방식으로 동작합니다

2024-12-12 16:24 UTC, jaeyeonme commented on docker/mysql/init.sql
> +    member_id BIGINT,
일반 회원들도 판매자로써 상품을 등록하고 관리할 수 있게 하려고 회원아이디를 넣었습니다

2024-12-12 16:30 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/PasswordConfig.kt
> +    fun passwordEncoder(): PasswordEncoder = BCryptPasswordEncoder()
찾아보니, 지금 사용하는 의존성만으로 더 강화된 인코더가 있군요! 바꿔보겠습니다 🙂

2024-12-12 17:41 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/RedisConfig.kt
> +    private fun createObjectMapper(): ObjectMapper {
지금방식은 `springSessionDefaultRedisSerializer()` 빈이 생성될 때마다 새로운 ObjectMapper 를 생성하는군요! 빈으로 등록하겠습니다. 😀

2024-12-12 17:44 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/SwaggerConfig.kt
> +                        "X-Auth-Token",
상수로 관리하겠습니다!

2024-12-12 17:47 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/interceptor/AuthenticationInterceptor.kt
> +        val sessionId = request.getHeader("X-Auth-Token")
이것도 상수로 공통관리 하겠습니다. 😀

2024-12-12 17:49 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/interceptor/PrimeMembershipInterceptor.kt
> +        if (!sessionUser.roles.contains("ROLE_PRIME")) {
이것두 상수로 관리하겠습니다! 🙂

2024-12-12 18:59 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/security/session/SessionUser.kt
> +        private const val serialVersionUID = 1L
확인해보니 동작을 잘합니다! 확인해보니, 

```kt
@Bean
fun springSessionDefaultRedisSerializer(): RedisSerializer<Any> {
    val objectMapper = ObjectMapper().apply {
        // ... ObjectMapper 설정들 ...
    }
    return GenericJackson2JsonRedisSerializer(objectMapper)
}
```

`GenericJackson2JsonRedisSerializer` 라는 Serializer 가 Jackson의 JSON 직렬화를 사용하는군요.!

1. 로그인 시도시
```kt
httpSession.setAttribute(SessionConstants.USER_KEY, SessionUser.from(member))
```

2. Spring Session이 데이터를 Redis에 저장할 때
 - `GenericJackson2JsonRedisSerializer`가 SessionUser 객체를 JSON으로 변환
 - 이 JSON 문자열이 Redis에 저장
 - Java의 기본 직렬화(Serializable)는 전혀 사용되지 않음

2024-12-12 19:02 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    fun login(@Valid @RequestBody request: LoginRequest): ResponseEntity<MemberResponse> {
생략하겠습니다! 🙂

2024-12-12 19:04 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    var memberId: Long? = null,
지금은 사용안하고 있으니 뺴겠습니다!

2024-12-12 19:12 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
Service Layer의 코드를 수정하는걸로 했는데, 어떻게 생각하시는지 궁금합니다!

```kt
// Service 수정
fun updateMember(member: Member, request: UpdateMemberRequest): MemberResponse {
    // 이미 조회된 엔티티를 사용
    request.name?.let { member.updateName(it) }
    request.password?.let {
        member.updatePassword(passwordEncoder.encode(it))
    }
    
    return MemberResponse.from(memberRepository.save(member))
}
```

2024-12-12 19:21 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/service/MembershipService.kt
> +        httpSession.setAttribute(USER_KEY, SessionUser.from(savedMember))
기존 세션 체크하는 로직을 넣겠습니다!

2024-12-12 19:24 UTC, jaeyeonme commented on src/main/resources/application.yml
> +          max-wait: -1ms
Redis의 Lettuce 커넥션 풀에서 무한정 대기입니다! 프로덕션 환경에서는 무한정 대기는 위험할 수 있으므로 타임아웃 값 설정하겠습니다.

2024-12-12 19:43 UTC, jaeyeonme commented on src/main/resources/application.yml
> +      cleanup-cron: "0 */30 * * * *"
Redis에 저장되는 세션의 유효 시간이 1시간(3,600초) 이므로 동일하게 설정해보겠습니다!

2024-12-13 14:33 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    member_id BIGINT,
그럼 일반회원외에 다른 판매자도 있나요?
그럴 때 여기에 있는 member_id 값은 무엇인가요?

2024-12-13 14:41 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
open-in-view 를 true 로 하셨나요? 
여기서 받은 파라미터 member가 영속성컨텍스트가 유지되는지 한번 확인부탁드려요.

2024-12-13 14:42 UTC, f-lab-saponin requested changes
리뷰반영 고생하셨습니다 ☺️ 한번만 더 확인부탁드립니다!

2024-12-14 03:31 UTC, jaeyeonme commented on docker/mysql/init.sql
> +    member_id BIGINT,
아직 그거 까지는 고려하지 않아서 없습니다! 만약에 그럴 경우에는, 모든 회원이 판매자가 될 수 있는 구조로 생각을 해서 넣었습니다!
Member 테이블의 ID를 Product의 테이블의 FK로 직접 참조하여 어떤 회원이 이 상품을 등록했는지 볼려고 넣었었습니다!

2024-12-14 04:41 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
false로 했습니다! `MemberControllerTest.http` 로 회원가입 -> 로그인 -> 프로필조회 순으로 했을 때,

```bash
Hibernate: select m1_0.member_id from members m1_0 where (m1_0.is_deleted = false) and m1_0.email=? fetch first ? rows only
Hibernate: insert into members (created_at,email,is_deleted,membership_end_date,membership_start_date,membership_type,name,password,updated_at,member_id) values (?,?,?,?,?,?,?,?,?,default)
Hibernate: select m1_0.member_id,m1_0.created_at,m1_0.email,m1_0.is_deleted,m1_0.membership_end_date,m1_0.membership_start_date,m1_0.membership_type,m1_0.name,m1_0.password,m1_0.updated_at from members m1_0 where (m1_0.is_deleted = false) and m1_0.email=?
Hibernate: select m1_0.member_id,m1_0.created_at,m1_0.email,m1_0.is_deleted,m1_0.membership_end_date,m1_0.membership_start_date,m1_0.membership_type,m1_0.name,m1_0.password,m1_0.updated_at from members m1_0 where m1_0.member_id=? and (m1_0.is_deleted = false)
```

회원가입
```bash
{
  "id": 1,
  "email": "test@example.com",
  "name": "TestUser",
  "membershipType": "NORMAL",
  "membershipStartDate": null,
  "membershipEndDate": null
}
```

로그인
```bash
{
  "id": 1,
  "email": "test@example.com",
  "name": "TestUser",
  "membershipType": "NORMAL",
  "membershipStartDate": null,
  "membershipEndDate": null
}
```

프로필조회
```bash
{
  "id": 1,
  "email": "test@example.com",
  "name": "TestUser",
  "membershipType": "NORMAL",
  "membershipStartDate": null,
  "membershipEndDate": null
}
```

잘 나옵니다!

2024-12-14 05:01 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
현재 구조에서 SessionUser를 통해 ID를 가져온 후 다시 DB에서 Member를 조회하는 문제로 DB를 2번 조회하는 것 같습니다. SessionUser에 필요한 기본 정보를 더 포함시키고, ArgumentResolver와 MemberService를 수정하여 불필요한 DB 조회를 줄이는 방향으로 리팩토링 하겠습니다!

2024-12-14 10:02 UTC, jaeyeonme commented
배포된 Spring Boot 서버에서 `'NOAUTH Authentication required'` 에러가 발생하여 체크해봤는데, 기존 코드에서 `@Value` 어노테이션으로 주입받는 변수명과 RedisStandaloneConfiguration에 설정하는 변수명이 동일해서 충돌이 나서 수정했습니다.

2024-12-14 15:42 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
updateMember 할 때, 업데이트 전에 조회 쿼리가 한번 더 실행될거같은데, 한번 확인가능하실까요?

2024-12-14 15:43 UTC, f-lab-saponin requested changes
updateMember 한번만 확인부탁드려요!

2024-12-15 02:11 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
```bash
--- 회원가입
Hibernate: select m1_0.member_id from members m1_0 where (m1_0.is_deleted = false) and m1_0.email=? fetch first ? rows only
Hibernate: insert into members (created_at,email,is_deleted,membership_end_date,membership_start_date,membership_type,name,password,updated_at,member_id) values (?,?,?,?,?,?,?,?,?,default
--- 로그인
Hibernate: select m1_0.member_id,m1_0.created_at,m1_0.email,m1_0.is_deleted,m1_0.membership_end_date,m1_0.membership_start_date,m1_0.membership_type,m1_0.name,m1_0.password,m1_0.updated_at from members m1_0 where (m1_0.is_deleted = false) and m1_0.email=?
--- 프로필 정보 수정
Hibernate: select m1_0.member_id,m1_0.created_at,m1_0.email,m1_0.is_deleted,m1_0.membership_end_date,m1_0.membership_start_date,m1_0.membership_type,m1_0.name,m1_0.password,m1_0.updated_at from members m1_0 where m1_0.member_id=? and (m1_0.is_deleted = false)
Hibernate: select m1_0.member_id,m1_0.created_at,m1_0.email,m1_0.is_deleted,m1_0.membership_end_date,m1_0.membership_start_date,m1_0.membership_type,m1_0.name,m1_0.password,m1_0.updated_at from members m1_0 where m1_0.member_id=? and (m1_0.is_deleted = false)
Hibernate: update members set email=?,is_deleted=?,membership_end_date=?,membership_start_date=?,membership_type=?,name=?,password=?,updated_at=? where member_id=?
```

체크해보니,

1. 첫 번째 SELECT 쿼리
```kt
public Any? resolveArgument(...) {
    // CurrentUserArgumentResolver에서 실행
    return memberRepository.findByIdOrNull(sessionUser.id)
}
```

2. 두 번째 SELECT 쿼리
```kt
@Transactional
fun updateMember(member: Member, request: UpdateMemberRequest): MemberResponse {
    // 여기서 member는 새로운 트랜잭션에서 다시 조회됨
    request.name?.let { member.updateName(it) }
    request.password?.let { member.updatePassword(passwordEncoder.encode(it)) }
    return MemberResponse.from(memberRepository.save(member))
}
```

새로운 트랜잭션이 시작될 때 영속성 컨텍스트가 새로 생성되면서, 엔티티를 다시 조회하는군요. 수정하겠습니다!

2024-12-15 10:02 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
오 수정하신 코드를 보아하니 memberRepository.save(member) 를 삭제하셨는데,
정상적으로 업데이트가 진행된걸까요?
open-in-view 를 false 로 하셨다해서, memberService.updateMember() 에 영속성 컨텍스트가 유지되는지 여부가 궁금했었거든요!
업데이트가 되면 어디서 되고있는걸까요?

2024-12-15 10:31 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
1. 회원가입 과정
```bash
-- 1. 이메일 중복 체크
Hibernate: select m1_0.member_id from members m1_0 where (m1_0.is_deleted = false) and m1_0.email=? fetch first ? rows only

-- 2. 회원 정보 저장
Hibernate: insert into members (...) values (...)
```

2. 로그인 과정
```bash
-- 이메일로 회원 조회
Hibernate: select m1_0.member_id, ... from members m1_0 where (m1_0.is_deleted = false) and m1_0.email=?
```

3. 프로필 정보 수정
```bash
-- CurrentUserArgumentResolver에서 회원 조회
Hibernate: select m1_0.member_id, ... from members m1_0 where m1_0.member_id=? and (m1_0.is_deleted = false)
```
```json
{
  "id": 1,
  "email": "test@example.com",
  "name": "UpdatedName",  // 변경된 이름이 반영됨
  "membershipType": "NORMAL",
  "membershipStartDate": null,
  "membershipEndDate": null
}
````

CurrentUserArgumentResolver에서의 엔티티 조회
```kt
class CurrentUserArgumentResolver {
    fun resolveArgument(...): Any? {
        val member = memberRepository.findByIdOrNull(sessionUser.id)
        // 여기서 조회된 member는 메서드가 끝나면서
        // 영속성 컨텍스트가 종료되어 준영속 상태가 됨
        return member
    }
}
```

컨트롤러에서 서비스 메서드 호출
```kt
@RestController
class MemberController {
    fun updateProfileDetails(...) {
        // 이 시점의 member는 준영속 상태입니다
        memberService.updateMember(member, request)
    }
}
```

서비스 메서드에서의 트랜잭션 처리
```kt
@Service
@Transactional
class MemberService {
    fun updateMember(member: Member, request: UpdateMemberRequest) {
        // @Transactional로 인해 새로운 영속성 컨텍스트가 시작되고
        // 준영속 상태였던 member는 이 시점에서 
        // 새로운 영속성 컨텍스트에 자동으로 병합(merge)됩니다
        
        request.name?.let { member.updateName(it) }
        // 이제 영속 상태가 된 member의 변경사항이
        // 더티 체킹의 대상이 됩니다
    }
}
```

영속성 컨텍스트와 트랜잭션


- @Transactional 어노테이션으로 인해 새로운 영속성 컨텍스트가 시작됩니다
- CurrentUserArgumentResolver에서 준영속 상태로 전달된 member는 트랜잭션 시작과 함께 자동으로 영속 상태로 병합됩니다
- 트랜잭션이 종료될 때 영속성 컨텍스트의 변경사항이 자동으로 데이터베이스에 반영됩니다(더티 체킹)"

2. 더티 체킹(Dirty Checking)의 동작
```kt
member.updateName(it)  // 엔티티 수정
// 명시적인 save() 호출이 없어도
// 트랜잭션 종료 시점에 변경사항이 감지되어 UPDATE 쿼리가 실행
```

3. 실제 업데이트가 일어나는 시점
```kt
@Transactional
fun updateMember(...) {
    member.updateName(it)     // 1. 엔티티 변경
    // 메소드 종료          // 2. 트랜잭션 커밋 시도
    // 트랜잭션 커밋 시점    // 3. 더티체킹으로 변경감지
    // 실제 UPDATE 쿼리 실행 // 4. 데이터베이스에 반영
}
```
따라서 memberRepository.save(member)가 없어도 업데이트가 정상적으로 동작하는 이유는:

1. @Transactional 어노테이션으로 인해 트랜잭션이 보장됩니다.
2. member 객체가 영속 상태이므로 더티 체킹이 가능합니다.
3. 트랜잭션 종료 시점에 변경감지가 동작하여 UPDATE 쿼리가 자동으로 실행됩니다.

제가 놓치고 있는게 있을까요?!

2024-12-15 16:00 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
OSIV 가 False인 상황에서, memberService 에서 새로운 Member 엔티티 조회(findByIdOrNull) 하는 방식으로 수정했습니다!

2024-12-15 16:01 UTC, jaeyeonme commented
멘토님 수정하고, local 상황에서도 Redis 문제없이 진행되게 하려고, local용 `docker-compose.yml` 을 만들었는데, `.env` 이건 README에 따로 만들어서 비밀번호 넣으면 된다고 공지하는게 좋을까요?! 아니면 다른 좋은 방법이 있는지 잘 모르겠습니다!

2024-12-17 13:31 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
혹시 @CurruentUser 했을 때 member 가 아닌 memberId 를 가져오도록 하면 어떨까요?
조회 로직을 제거해서 뒤에서 조회로직과 겹치지 않도록요!

2024-12-17 13:33 UTC, f-lab-saponin approved these changes
해당 PR 이 오래 열려있어서 다음 진행을 위해 일단 승인드립니다. 아래 내용 한번 확인해봐주세요!
고생하셨습니다 🙂👍👍

1) 로컬에서 실행할 수 있도록 테스트컨테이너 잘 활용해셨네요. 근데 테스트코드에서 말고 이렇게 써보는건 용도가 맞는지는 모르겠는데 괜찮을 것 같기도 하네요.
2) 이부분도 한번 반영가능하신지 봐주세요.
> 혹시 @CurruentUser 했을 때 member 가 아닌 memberId 를 가져오도록 하면 어떨까요?
조회 로직을 제거해서 뒤에서 조회로직과 겹치지 않도록요!

2024-12-17 20:33 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/member/controller/MemberController.kt
> +    }
이전: @CurrentUser member: Member
현재: @CurrentUser memberId: Long

으로 해서 Controller 파라미터 변경했습니다.

2024-12-17 20:34 UTC, jaeyeonme commented
TestContainer 가 주로 테스트 환경을 위한 라이브러리가 맞는걸로 알고 있습니다! 그런데 'implementation' 스코프로 추가한 이유는, 
prod 환경에서는 실제 Redis를 사용하고, local 환경에서만 TestContainers가 활성화되도록 @Profile로 분리했습니다. 우선 더 나은 방안이 있으면, 추후에 변경하겠습니다!

또한, @CurruentUser 했을 때 member 가 아닌 memberId 를 가져오도록 리팩토링했습니다!

2024-12-17 20:37 UTC, merged