[#8] Order, Payment Domain 구현
f-lab-edu/event-blackfriday pull request #17
Opened 2024-12-26 15:07 UTC by jaeyeonme

- [x] #11 

## Changes
### Domain Layer
- Order/Payment 도메인 구현
  - Order, OrderItem 엔티티 설계 및 구현
  - Payment 엔티티 설계 및 구현
  - OrderStatus를 통한 주문 상태 관리 (WAITING, PENDING, IN_PROGRESS, READY_FOR_PAYMENT, CANCELLED)
  - PaymentStatus를 통한 결제 상태 관리 (PENDING, COMPLETED, CANCELLED)

### Application Layer
- [x] 주문 관리 서비스 구현
  - 주문 생성/취소/조회 기능 구현
  - 주문 상태 관리 및 상태 전이 규칙 구현
  - 주문 소유권 검증 로직 구현
  - 재고 관리 연동 (상품 재고 감소/증가)

- [x] 결제 서비스 구현
  - 결제 생성/취소/조회 기능 구현
  - 결제 금액 검증 로직 구현
  - 결제 소유권 검증 로직 구현

### Infrastructure Layer
- [x] ID 생성기 구현
  - Snowflake 알고리즘 기반 ID 생성기 구현
  - OrderNumberGenerator, PaymentNumberGenerator 구현

- [x] API 문서화
  - Swagger 3.0 기반 API 문서화
  - Order/Payment API 태그 설정
  - Request/Response DTO 문서화

### Test Layer
- [x] 테스트 코드 작성
  - OrderServiceTest 구현
  - PaymentServiceTest 구현
  - OrderController/PaymentController HTTP 테스트 구현
  - Fixture 클래스를 통한 테스트 데이터 관리

### Database
- [x] 스키마 설정
  - Orders, OrderItems 테이블 설계
  - Payments 테이블 설계
  - member_id 외래키 및 인덱스 추가
  - Soft Delete 구현 (@SQLRestriction)

2024-12-27 15:12 UTC, f-lab-saponin requested changes
고생하셨습니다!!!
코멘트 드린내용 봐주시고, 가능한부분은 한번 반영해주세요! 감사합니다 ☺️

2024-12-27 15:12 UTC, f-lab-saponin commented on build.gradle.kts
> +    testImplementation("com.appmattus.fixture:fixture:1.2.0")
이건 혹시 어떤장점으로 도입하셨을까요?🙂

2024-12-27 15:12 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    member_id BIGINT NOT NULL,
카테고리에 왜 member_id 가 필요할까요?

2024-12-27 15:12 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    member_id BIGINT NOT NULL,
상품에도 회원아이디가 있는데 의도가궁금합니다!

2024-12-27 15:12 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    order_number VARCHAR(255) NOT NULL UNIQUE,
수량을 말하는걸까요? 그럼 quantity 가 어떨가요?

2024-12-27 15:12 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    timeout_at DATETIME(6),
이건 무슨 용도인가요? 🧐

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/SnowflakeOrderNumberGenerator.kt
> +    }
이 id 는 순차적인지, 몇자리인지 등등 어떤 특징을 가지는지 상수로 있으면 좋겠네요!

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +
상품 카테고리가 memberId 와 무슨 연관성이있나요~?

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/Order.kt
> +    val id: Long? = null,
테이블 컬럼도 id 로 통일하면 어떨가요? 🙂

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/Order.kt
> +            OrderStatus.CANCELLED -> emptySet()
각 상태를 나눈 기준이있을가요? 🧐

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/OrderItem.kt
> +    val id: Long? = null,
이것두요!

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/repository/OrderRepository.kt
> +        AND (:status IS NULL OR o.status = :status)
status 는 언제 null 일수있나요?

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/service/OrderService.kt
> +        val orderItems = orderItemRepository.findByOrderId(order.id!!)
!! 사용대신 null 처리를 따로 해볿수있을가요? 🙂

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/payment/domain/enum/PaymentStatus.kt
> +}
강제로 취소한 상태랑 실패한 상태랑 구분이 있으면 운영이 쉬워보이네요!

2024-12-27 15:12 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/payment/service/PaymentService.kt
> +    }
Payment 가 이역할을 맡아도 되겠네요!

2024-12-28 01:12 UTC, jaeyeonme commented on build.gradle.kts
> +    testImplementation("com.appmattus.fixture:fixture:1.2.0")
테스트마다 Member나 Product 같은 객체를 반복해서 생성하는 대신, fixture를 사용하면 이러한 반복 작업을 줄일 수 있어서 도입했습니다.

2024-12-28 01:16 UTC, jaeyeonme commented on docker/mysql/init.sql
> +    member_id BIGINT NOT NULL,
회원가입 -> 로그인 -> 카테고리 등록 -> Product 등록 -> Order 생성 로직으로 하고 있는데, 로그인 하고 비회원인 경우 등록이 안되게 하기 위해 넣었습니다! 

다른 방법이 있는지 궁금합니다

2024-12-28 01:34 UTC, jaeyeonme commented on docker/mysql/init.sql
> +    timeout_at DATETIME(6),
추후에 타임딜에 넣을 것이었습니다! 지우겠습니다

2024-12-28 01:35 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/config/SnowflakeOrderNumberGenerator.kt
> +    }
그렇군요! 리팩토링 해보겠습니다 🙂

2024-12-28 15:08 UTC, f-lab-saponin requested changes

2024-12-28 15:08 UTC, f-lab-saponin commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/common/ProductFixture.kt
> +    private val fixture = kotlinFixture {
이건 사용을 안하는데 왜 만든걸까요? 🧐

2024-12-28 15:08 UTC, f-lab-saponin commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/common/OrderFixture.kt
> +        orderNumber: String = fixture(),
이건 올바른 사용이 맞나요? 직관적으로 볼 때 String 값이 와야하는데 fixture() 를 하면 자동으로 미리 만들어놓은 orderNumber 값이 매핑이 되는건가요?

2024-12-28 15:08 UTC, f-lab-saponin commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/common/CategoryFixture.kt
> +    private val fixture = kotlinFixture {
여기도 사용이 안되고, 밑에는 따로 Category 를 만들고있어요..!

2024-12-28 15:08 UTC, f-lab-saponin commented on build.gradle.kts
> +    testImplementation("com.appmattus.fixture:fixture:1.2.0")
밑에 코멘트 새로 추가한 것 한 번 확인부탁드려요! 🙂

2024-12-28 15:10 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    member_id BIGINT NOT NULL,
카테고리를 만든 판매자 id 를 넣고 싶은 모양인데, 일반회원 id 가 들어가는 뉘앙스인것처럼 보여 헷갈리네요 😢
필드명을 판매자로 바꿔보는건 어떨가요?

2024-12-28 15:10 UTC, f-lab-saponin commented on docker/mysql/init.sql
> +    timeout_at DATETIME(6),
아아 그렇다며 딱히 지울필요는 없습니다! 궁금해서 질문드린겁니다!

2024-12-30 04:35 UTC, jaeyeonme commented on docker/mysql/init.sql
> +    member_id BIGINT NOT NULL,
필드명을 수정해보겠습니다!

2024-12-30 04:36 UTC, jaeyeonme commented on docker/mysql/init.sql
> +    member_id BIGINT NOT NULL,
여기에도 필드명을 수정해보겠습니다.

2024-12-30 07:37 UTC, jaeyeonme commented on build.gradle.kts
> +    testImplementation("com.appmattus.fixture:fixture:1.2.0")
넵! 확인했습니다. 🙂

2024-12-30 07:38 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/Order.kt
> +    val id: Long? = null,
넵 id로 통일 시키겠습니다!

2024-12-30 07:38 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/OrderItem.kt
> +    val id: Long? = null,
여기두 통일시키겠습니다!

2024-12-30 07:50 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/OrderItem.kt
> +    val id: Long? = null,
나머지 도메인에도 통일시키는 걸루 리팩토링 하겠습니다!

2024-12-30 07:52 UTC, jaeyeonme commented on docker/mysql/init.sql
> +    order_number VARCHAR(255) NOT NULL UNIQUE,
수량은 아니구 주문번호(고유번호) 를 나타낸 필드 입니다!

2024-12-30 08:03 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/repository/OrderRepository.kt
> +        AND (:status IS NULL OR o.status = :status)
1. 사용자가 특정 상태(PENDING, IN_PROGRESS 등)의 주문만 조회하고 싶을 때 status 값을 지정하고,
2. 모든 상태의 주문을 보고 싶을 떄는 status 를 null로 전달합니다.

그래서, status 가 null인 경우는 "모든 상태의 주문을 조회하고 싶을 때" 입니다!

2024-12-30 08:04 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/service/OrderService.kt
> +        val orderItems = orderItemRepository.findByOrderId(order.id!!)
리팩토링 하겠습니다! 🙂

2024-12-30 08:15 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/payment/domain/enum/PaymentStatus.kt
> +}
리팩토링 하겠습니다!

2024-12-30 15:34 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/payment/service/PaymentService.kt
> +    }
이 부분도 Payment 도메인이 검증 로직을 직접 처리하는 걸로 리팩토링 하겠습니다!

2024-12-31 01:43 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/service/CategoryService.kt
> +
이것두 Seller 로 리팩토링했습니다!

2024-12-31 01:48 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/Order.kt
> +            OrderStatus.CANCELLED -> emptySet()
따로 나눈 기준은 없습니다!
1. 대기 상태: 접수(PENDING) 또는 취소가능
2. 접수 상태: 처리 중(IN_PROGRESS) 으로 진행하거나 취소 가능
3. 처리 중 상태: 결제 대기(READY_FOR_PAYMENT) 로 진행하거나 취소 가능
4. 결제 대기 상태: 취소만 가능
5. 취소 상태: 더 이상의 상태 변경 불가

이 프로세스로 진행되고 있습니다!

2024-12-31 01:50 UTC, jaeyeonme commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/common/ProductFixture.kt
> +    private val fixture = kotlinFixture {
다시 리팩토링 해보겠습니다!

2024-12-31 02:05 UTC, jaeyeonme commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/common/OrderFixture.kt
> +        orderNumber: String = fixture(),
factory 에서는 "ORDER-001"로 고정했지만, 여기서는 `fixture()`로 랜덤 생성으로 값이 다르군여! 다시 수정해보겠습니다.

2024-12-31 02:09 UTC, jaeyeonme commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/common/CategoryFixture.kt
> +    private val fixture = kotlinFixture {
여기도 동일하게 다시 리팩토링 하겠습니다!

2024-12-31 06:54 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/domain/Order.kt
> +            OrderStatus.CANCELLED -> emptySet()
더 간단한 프로세스로 리팩토링 하겠습니다!

2024-12-31 14:51 UTC, jaeyeonme commented
현재 주문 상태 흐름을 보면 

```text
WAITING -> PENDING -> IN_PROGRESS -> READY_FOR_PAYMENT
```

이 프로세스로 되고 있습니다. 그래서 더 단순화된 상태 흐름으로 리팩토링 했습니다.

1. WAITING (주문 생성)
2. PENDING_PAYMENT (결제 대기)
3. PAID (결제 완료)
4. CANCELLED (취소됨)

2025-01-01 16:26 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/repository/OrderRepository.kt
> +        AND (:status IS NULL OR o.status = :status)
모든 상태의 주문을 조회하고 싶을 때는 `status IS NULL` 조건을 제외하고 조회해야하지 않을까요~? 🧐

2025-01-01 16:28 UTC, f-lab-saponin approved these changes
리뷰 반영해주시느라 고생하셨습니다!!
추가적으로 코멘트 드린 부분만 확인해주시고 머지 부탁드려요!

2025-01-01 16:28 UTC, f-lab-saponin commented on build.gradle.kts
> +    testImplementation("com.appmattus.fixture:fixture:1.2.0")
이건 더이상 사용하지 않는 것 같아 제거해주셔도 될것같아요!
혹시나 사용중이시면 말씀부탁드립니다 :)

2025-01-02 00:58 UTC, jaeyeonme commented on build.gradle.kts
> +    testImplementation("com.appmattus.fixture:fixture:1.2.0")
리팩토링 후에 사용 안하고 있네요! 다시 제거하겠습니다 :)

2025-01-02 01:52 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/order/repository/OrderRepository.kt
> +        AND (:status IS NULL OR o.status = :status)
`status` 조건 자체를 제외하는게 맞군여! 다시 수정하겠습니다

2025-01-02 02:54 UTC, merged