[#1] 상품 도메인 구현
f-lab-edu/event-blackfriday pull request #3
Opened 2024-11-04 15:01 UTC by jaeyeonme

- [ ] #1 

## Changes
- **Core Domain**
  - BaseTimeEntity 추상 클래스 구현
    - `@MappedSuperclass`, `@EntityListeners` 설정
    - JPA Auditing 기반 시간 추적 (created_at, updated_at)
  - Product 엔티티 클래스 구현
    - Primary Constructor 패턴 적용
    - 필수 필드 정의 및 JPA 매핑 (`@Entity`, `@Column`)
    - 기본 재고 관리 메서드 구현

- **Domain Logic**
  - 도메인 불변식 검증
    - init 블록을 활용한 생성 시점 검증
    - require()를 통한 필수값 검증
  - 재고 관리 메서드
    - increaseStock(): 재고 증가 로직
    - decreaseStock(): 재고 감소 로직
    - 비즈니스 규칙 기반 유효성 검증

- **Testing**
  - Kotest BehaviorSpec 테스트 구현
    - given-when-then 패턴으로 시나리오 테스트
    - 도메인 규칙 검증 케이스 작성
  - 상품 생성 및 재고 관리 테스트
    - 정상 케이스 검증
    - 예외 케이스 검증

2024-11-05 14:55 UTC, f-lab-saponin requested changes
첫 리뷰네요. 코드 전반적으로 구성이 좋아보입니다. (AI 가한건가요? 😂)
고생하셨습니다! 제안드린 부분만 확인부탁드려요.

2024-11-05 14:55 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    var description: String,
상품명이나 설명이 무한정 길수는 없으니까 길이제한을 정하면 좋을 것 같아요.
데이터베이스 스키마를 정하는 부분이니 초반에 정책을 세우면 좋을 것 같습니다 🙂

2024-11-05 14:55 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    }
생성할 때 잘못된 값을 받았을 때 IllegalArgumentException 가 좋을지, 다른 예외가 좋을지 초반에 정하면 좋을 것 같아요!

2024-11-05 14:55 UTC, f-lab-saponin commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/product/domain/ProductTest.kt
> +class ProductTest : BehaviorSpec({
테스트 감사합니다 👍 깔끔하십니다

2024-11-05 14:55 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    var stockQuantity: Int,
재고수량에 대해서는 이렇게 상품에 곁달려있는 구조로 정하셨군요! (좋습니다)
1)만약 사용자가 많아 주문량이 많아진다거나 
2)재고업체가 여러군데여서 재고수량이 퍼져있거나
등등 재고수량을 어떻게 관리하면 좋을지 한번 생각만 해보시면 좋을 것 같아요.

2024-11-05 15:00 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    var description: String,
이 부분은 참고해서 수정해보겠습니다!

2024-11-05 15:01 UTC, jaeyeonme commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/product/domain/ProductTest.kt
> +class ProductTest : BehaviorSpec({
감사합니다 👍

2024-11-05 15:07 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    }
그렇지 않아도 다음 이슈 티켓에 예외 처리 구현에서 커스텀 예외로 하려고 준비중입니다 🙂

2024-11-05 15:27 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/product/domain/Product.kt
> +    var stockQuantity: Int,
1) 만약 사용자가 많아 주문량이 많아진다거나 -> 동시에 많은 주문이 들어오면 재고 수량을 정확하게 관리하기 어려울 수 있군요!
2) 재고업체가 여러군데여서 재고수량이 퍼져있거나 -> 상품의 재고가 여러 창고나 공급처에 분산되어 있다면, 단일 컬럼으로는 힘들겠군요!

이 부분도 고민해보겠습니다.

2024-11-06 13:57 UTC, f-lab-saponin approved these changes
고생하셨습니다 다음부분으로 넘어가볼까요!

2024-11-06 14:08 UTC, merged