[#2] 예외 처리 구현
f-lab-edu/event-blackfriday pull request #4
Opened 2024-11-07 04:47 UTC by jaeyeonme

- [x] #2 

## Changes
- [x] ErrorCode & Response
   - 공통/도메인별 에러 코드 정의했습니다.
   - 표준화된 에러 응답 포맷 설계했습니다.

- [x] Exception Classes
   - BlackFridayException: 기본 예외 클래스 정의했습니다.
   - ProductException: 상품 도메인 전용 예외 정의했습니다.

- [x] Global Exception Handler
   - @RestControllerAdvice로 전역 예외 처리 했습니다.
   - 예외별 HTTP 상태 코드 매핑 했습니다.

- [x] Product Entity Updates
   - 유효성 검증에 커스텀 예외 적용 했습니다.
   - 재고 관리 메서드에 예외 처리 추가 했습니다.

- [x] Test Updates
   - 커스텀 예외 테스트 케이스 추가 했습니다.
   - 테스트 독립성 보장을 위한 수정 했습니다.

## ❓ 질문 사항
GlobalExceptionHandler로 전역 예외 처리를 구현했는데, Product 도메인에 대해 ProductException을 따로 만들어 관리하는 것이 좋은 방식인지 궁금합니다.

2024-11-07 04:48 UTC, jaeyeonme commented
이번에는 기존 세팅 파일 업데이트 때문에 파일이 좀 많아졌습니다!

2024-11-07 14:30 UTC, f-lab-saponin requested changes
와 코드가 예쁩니다 고생하셨습니다.
혹시 직접 예외를 응답받아보셨나요?
그 결과까지 PR 본문에 예시로 담아주시면 이해가 쉬울것같아요 :)

2024-11-07 14:30 UTC, f-lab-saponin commented on .editorconfig
> +[*.{kt,kts}]
👍

2024-11-07 14:30 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/exception/ErrorModel.kt
> +    INVALID_INPUT_VALUE(HttpStatus.BAD_REQUEST, "C-001", "유효하지 않은 입력입니다."),
C 대신 COMMON 으로 하면 어떤 장단점이 있을까요?
문자열 비용 vs 커뮤니케이션 이해 비용을 한 번 생각해봅시다.

2024-11-07 14:30 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/global/GlobalExceptionHandler.kt
> +        return ResponseEntity(response, ex.errorCode.status)
status 가 response.body 안에도 있는 것 같고, ResponseEntity.status 에도 중복으로 있는 것 같아요.
이런 구조가 필요할까요?

2024-11-07 14:46 UTC, jaeyeonme commented
받아보지는 않았지만, 이번 기회에 받아서 한번 PR에 업데이트 해보겠습니다 :)

2024-11-07 17:33 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/exception/ErrorModel.kt
> +    INVALID_INPUT_VALUE(HttpStatus.BAD_REQUEST, "C-001", "유효하지 않은 입력입니다."),
`COMMON` 으로 하게 되면, 약간의 문자열 길이 증가보다 명확한 의미 전달이 될 것 같습니다.

2024-11-07 17:58 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/global/GlobalExceptionHandler.kt
> +        return ResponseEntity(response, ex.errorCode.status)
HTTP 응답 상태 코드는 `ResponseEntity` 의 `status` 로 전달이 되겠군요. 일관성을 위해 제거하는 게 맞는 것 같습니다!

2024-11-07 18:33 UTC, jaeyeonme commented
예외 응답 예시로 직접 응답 받아서 확인했습니다!

2024-11-08 11:58 UTC, f-lab-saponin approved these changes
고생하셨습니다 승인드립니다!
머지 방식을 squash merge 로 하면 이 PR 이 한 커밋으로 정리되어 깔끔하게 머지되는데 한번 고민해봐주세요!

그리고 PR 본문에 질문사항에 답변드립니다
도메인 별로 나누면 예외가 어디서 발생했는데 명시적으로 알 수 있어서, 나중에 추적하기 좋을 것 같아요. 단점으로는 예외가 좀 많아질 수도 있겠죠?
예를 들어 같은 내용인데 ProductIllegalStateException, OrderIllegalStateException 등등 겹칠 수도 있겠죠. 이건 고민해보시고 적용해주세요 :)

2024-11-08 13:33 UTC, jaeyeonme commented
감사합니다! 브랜치 전략도 Github Flow로 전환하여 feature -> main으로 squash merge 하는 방식으로 진행하도록 하겠습니다!

도메인별로 구체적인 예외를 만들면, 어느 도메인에서 발생했는지 바로 알기 쉽겠군요! 이것도 반영해보도록 하겠습니다.~

2024-11-08 14:49 UTC, merged