[#4] 카테고리 도메인 구현
f-lab-edu/event-blackfriday pull request #7
Opened 2024-11-09 12:19 UTC by jaeyeonme

- [x] #5 

## Changes
- [x] Category Entity
   - 계층 구조 구현 (parent-child 관계)
   - Product 단방향 매핑 추가
   - 기본 할인율 필드 추가

- [x] Domain Methods
   - addChild: 계층 구조 관리
   - removeChild: 하위 카테고리 제거
   - updateDiscountRate: 할인율 관리

- [x] Validation Logic
   - 카테고리명 길이 검증 (2-50자)
   - 계층 깊이 제한 (최대 4단계)
   - 할인율 범위 검증 (0-90%)

- [x] Exception Classes
   - CategoryException 추가
   - 도메인별 에러 코드 정의
   - 검증 실패 시 예외 처리

- [x] Test Cases
   - Entity 생성/수정 테스트
   - 계층 구조 관리 테스트
   - 도메인 검증 테스트

2024-11-09 14:28 UTC, f-lab-saponin requested changes
고생하셨습니다!! 👍👍👍

2024-11-09 14:28 UTC, f-lab-saponin commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/category/domain/CategoryTest.kt
> +            }
이거는 왜 90% 는 제한을 두셨는지 궁금하네요 :)

2024-11-09 14:28 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +        if (discountRate < BigDecimal.ZERO || discountRate > BigDecimal("90")) {
매직넘버 90 을 상수로 선언해보면 어떨까요?

2024-11-09 14:28 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +        if (this.depth >= 4) {
여기두요!

2024-11-09 14:28 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    val children: MutableList<Category> = mutableListOf(),
Category 는 자기 참조 구조를 가지는데, 한 테이블로 표현할 때 장단점 생각해보시면 좋겠고,
(예를 들어 재귀적인 조회가 필요한 경우가 있을 수 있는데 depth 가 깊어질 수록 좀 복잡해질 수도 있을것같아요.)
다른 방법도 생각해봤으면 좋겠어요. 예를 들어 Closure 테이블을 찾아보시면 좋을 것 같아요. (반드시 변경하라는 건 아니고, 선택한 이유를 말씀해주시면 좋겠습니다!)

2024-11-09 14:28 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +}
JPA 에서 이부분 실행시 자녀객체가 실제로 사라질까요? orphan 관련 옵션도 한번 생각해보면 좋을것같아요.
또 다른 관점으로는 데이터를 반드시 삭제하는게 좋은가? 도 생각해보면 좋을것같아요.

2024-11-09 16:10 UTC, jaeyeonme commented on src/test/kotlin/com/jaeyeon/blackfriday/domain/category/domain/CategoryTest.kt
> +            }
할인율에 대한 제한을 말씀하시는걸까요?! 90%는 제가 임의로 설정했었네요! 이것두 바꿔놓도록 하겠습니다. 아마존 정책을 찾아보니

주요 할인율 예시:
- Amazon Devices: 40% off (Echo, Fire TV sticks)
- Clothing: 60% off (activewear, luggage & shoes)
- Toys: up to 50% off
- Vacuums: up to 55% off
- Echo Dot: 58% off ($49.99 → $22.99)
- Fire TV Stick: 50% off ($39.99 → $19.99)
실제 Amazon의 할인율을 보면:
1. 대부분의 할인이 40-60% 범위
2. 특별한 경우에도 70% 정도가 최대
3. 90%와 같은 극단적인 할인은 거의 없음

2024-11-09 16:16 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +        if (discountRate < BigDecimal.ZERO || discountRate > BigDecimal("90")) {
매직넘버를 상수로 분리하겠습니다!

2024-11-09 16:16 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +        if (this.depth >= 4) {
여기두 분리하겠습니다!

2024-11-09 16:37 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    val children: MutableList<Category> = mutableListOf(),
멘토님! 제가 구현한 카테고리 구조는 이렇게 되어있습니다!

```text
전자제품
├── 모바일
│   ├── 스마트폰
│   │   └── 안드로이드
│   └── 태블릿
└── 가전
    └── TV
```

멘토님께서 말씀하신 Closure Table 방식도 찾아보았습니다:

```text
[CategoryClosure 테이블]
ancestor_id | descendant_id | depth
1           | 1             | 0    (전자제품 → 전자제품)
1           | 2             | 1    (전자제품 → 모바일)
1           | 3             | 2    (전자제품 → 스마트폰)
1           | 4             | 3    (전자제품 → iPhone)
2           | 2             | 0    (모바일 → 모바일)
2           | 3             | 1    (모바일 → 스마트폰)
2           | 4             | 2    (모바일 → iPhone)
3           | 3             | 0    (스마트폰 → 스마트폰)
3           | 4             | 1    (스마트폰 → iPhone)
4           | 4             | 0    (iPhone → iPhone)
```

현재 구현 방식의 장단점을 분석해보았습니다:

**현재 구현 (Self-Referential)**
```kt
@ManyToOne(fetch = FetchType.LAZY)
var parent: Category? = null,

@OneToMany(mappedBy = "parent")
val children: MutableList<Category> = mutableListOf()
```

장점:
- 구현이 직관적이고 단순함
- 기본적인 부모-자식 관계 표현이 쉬움
- JPA에서 기본적으로 잘 지원됨

단점:
- 계층 구조가 깊어질수록 재귀적 쿼리가 필요해 성능 저하
- 전체 계층 구조 조회 시 여러 번의 쿼리 발생
- 특정 노드의 모든 조상/자손 조회가 복잡함


**Closure Table 방식**

```kt
@Entity
class CategoryClosure(
    @Id @GeneratedValue
    val id: Long? = null,

    @ManyToOne
    val ancestor: Category,

    @ManyToOne
    val descendant: Category,

    val depth: Int
)
```

장점:
- 계층 구조 조회가 효율적 (한 번의 쿼리로 가능)
- 조상/자손 관계를 직접 저장해 조회 성능이 좋음
- 계층 구조 변경이 용이함

단점:
- 추가 테이블 필요
- 데이터 중복 저장
- 구현이 더 복잡함

현재는 카테고리 depth가 4단계로 제한되어 있어 재귀 쿼리의 부담이 크지 않을 것으로 판단하여 Self-Referential 방식을 선택했습니다.
혹시 이 방식에 대해 멘토님의 의견을 여쭤보고 싶습니다! 🙂!
더 고민해 볼만한 부분이 있을까요?!

2024-11-09 17:04 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +}
확인해보니, 컬렉션에서만 제거되고, 참조관계만 제거되는군요! `orphanRemoval` 이걸로 삭제 (Soft Delete) 까지 반영해보겠습니다.

2024-11-10 10:45 UTC, jaeyeonme commented
멘토님께 다시 요청 드리고, 그 뒤에 다시 Commit 한 파일이 있습니다!

2024-11-10 14:15 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +}
카테고리를 테이블에서 완전히 삭제하는게 맞는지, 아니면 flag 로 설정하는게 좋을지도 고민해보면 좋을 것 같아요!

2024-11-10 14:25 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    var descendantClosures: MutableList<CategoryClosure> = mutableListOf(),
Category Closure 테이블이 있는데 Category 에 여전히 parent, child 가 있네요. 중복해서 사용하시는건가요?

2024-11-10 14:43 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +}
삭제되었다는 표시(flag)만 해두는 방식으로 적용했습니다!!

2024-11-10 14:45 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    var descendantClosures: MutableList<CategoryClosure> = mutableListOf(),
헛.. Closure Table 만으로 사용해서 중복을 제거하겠습니다!

2024-11-10 17:06 UTC, jaeyeonme commented
멘토님! 코드리뷰 반영하면서 전체적으로 리팩토링 진행 좀 했습니다!

2024-11-12 13:10 UTC, f-lab-saponin requested changes
리뷰드립니다 👍

2024-11-12 13:10 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/CategoryClosure.kt
> +}
(질문)
_를 필드앞에 붙인 이유는 무엇인가요?
그럼 반대로 다른 엔티티에서는 _를 안붙힌 이유는 뭔가요?

2024-11-12 13:10 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +        get() = _discountRate
여기두요!

2024-11-12 13:10 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    private fun addDirectRelation(child: Category) {
1. 이 밑으로 private method 가 상당히 많은데 각각이 다 Category 엔티티 안에 있어야할까요?
이에 반해 CategoryClosure 안에 메소드는 하나도 없네요.
책임과 역할 관점에서 어떻게 하면 좋을까요?


2. 추가적으로 지금 당장 필요한 메소드를 구현했으면 좋겠습니다. 
이 메소드가 필수적이라면 테스트를 만들어서 이게 왜 필요한 코드인지 명시했으면 좋겠어요!

2024-11-12 14:10 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/CategoryClosure.kt
> +}
불변성 때문에 사용했습니다! 그런데, `val` 로 선언해도 불변성이 보장이 되는군요! 단순한 엔티티 관계에서는 간단하게 가는 게 더 좋을 것 같습니다. 다시 수정해보겠습니다.

2024-11-12 14:11 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +        get() = _discountRate
여기두 다시 수정해보겠습니다!

2024-11-12 14:15 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/domain/category/domain/Category.kt
> +    private fun addDirectRelation(child: Category) {
현재 구조에서는 Category 엔티티가 계층구조 관리와 관련된 모든 책임을 가지고 있고, CategoryClosure는 단순히 데이터만 담고 있는 상황이군요! 이 부분도 다시 리팩토링 해보겠습니다.

2024-11-12 19:13 UTC, jaeyeonme commented
멘토님! 요구사항을 다시 재수정 하여서 PR 내용 수정도 하고, 그거에 맞게 다시 리팩토링 하였습니다!

2024-11-13 14:57 UTC, f-lab-saponin approved these changes
이 PR 이 오랫동안 열려있어서 일단 승인드립니다!
리뷰드린부분만 수정해주시고 머지해주셔도 좋을것같아요

2024-11-13 14:57 UTC, f-lab-saponin commented on src/main/kotlin/com/jaeyeon/blackfriday/common/exception/ErrorModel.kt
> +    INVALID_CATEGORY_CLOSURE_DEPTH(HttpStatus.BAD_REQUEST, "CATEGORY-005", "Closure depth는 0 이상이어야 합니다"),
003이 누락됐네요 !

2024-11-13 14:58 UTC, jaeyeonme commented on src/main/kotlin/com/jaeyeon/blackfriday/common/exception/ErrorModel.kt
> +    INVALID_CATEGORY_CLOSURE_DEPTH(HttpStatus.BAD_REQUEST, "CATEGORY-005", "Closure depth는 0 이상이어야 합니다"),
헛.. 이 부분만 빠르게 수정하고, 다음 꺼 진행하겠습니다!

2024-11-13 17:39 UTC, merged